### ISSUE TITLE
How to change backbone model

### ISSUE THREAD

**Issue by ZJUGuoXiangyu** [datvuthanh/HybridNets#42]

**Comment by HTR625** [comment]
Hello, I am also working on this issue now, what method did you use. I replaced the encoder with timm-regnet, but the network will report the following error, please also point me out

Traceback (most recent call last):
  File "D:\HybridNets-main\train.py", line 320, in <module>
    train(opt)
  File "D:\mypyfile\HybridNets-main-revise\train.py", line 152, in train
    model = HybridNetsBackbone(num_classes=len(params.obj_list), compound_coef=opt.compound_coef,
  File "D:\HybridNets-main\backbone.py", line 95, in __init__
    self.encoder = get_encoder(          # 'efficientnet-b' + str(self.backbone_compound_coef[compound_coef])
  File "D:\HybridNets-main\encoders\__init__.py", line 67, in get_encoder
    encoder = Encoder(**params)
  File "D:\HybridNets-main\encoders\timm_regnet.py", line 8, in __init__
    super().__init__(**kwargs)
  File "D:\miniconda\envs\yo\lib\site-packages\timm\models\regnet.py", line 389, in __init__
    stem_width = cfg.stem_width
AttributeError: 'dict' object has no attribute 'stem_width'
