### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by wkgit88** [datvuthanh/HybridNets#99]
When I was training in BDD100k , error occurred. I changed the num_workers from 8 to 1 but this still happened:

xception ignored in: <function Image.__del__ at 0x000001E7CCBA4040>
Traceback (most recent call last):
  File "C:\anaconda\envs\multi\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
xception ignored in: <function Variable.__del__ at 0x000001E7CBD56700>
Traceback (most recent call last):
  File "C:\anaconda\envs\multi\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001E7CBD56700>
Traceback (most recent call last):
  File "C:\anaconda\envs\multi\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001E7CBD56700>
Traceback (most recent call last):
  File "C:\anaconda\envs\multi\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001E7CBD56700>
Traceback (most recent call last):
  File "C:\anaconda\envs\multi\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread

Anyone can help me? Thanks a lot

**Comment by AntonioConsiglio** [comment]
Try to set num_worker to 0. Then let us know if you have same error.
